// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TicTacToeMoveResultDto
    {
        /// <summary>
        /// Initializes a new instance of the TicTacToeMoveResultDto class.
        /// </summary>
        public TicTacToeMoveResultDto() { }

        /// <summary>
        /// Initializes a new instance of the TicTacToeMoveResultDto class.
        /// </summary>
        public TicTacToeMoveResultDto(int? move = default(int?), string azurePlayerSymbol = default(string), string humanPlayerSymbol = default(string), string winner = default(string), IList<int?> winPositions = default(IList<int?>), IList<string> gameBoard = default(IList<string>))
        {
            Move = move;
            AzurePlayerSymbol = azurePlayerSymbol;
            HumanPlayerSymbol = humanPlayerSymbol;
            Winner = winner;
            WinPositions = winPositions;
            GameBoard = gameBoard;
        }

        /// <summary>
        /// move: Computer's move (0..8)
        /// </summary>
        [JsonProperty(PropertyName = "move")]
        public int? Move { get; set; }

        /// <summary>
        /// Azure Player's Symbol "X" or "O"
        /// </summary>
        [JsonProperty(PropertyName = "azurePlayerSymbol")]
        public string AzurePlayerSymbol { get; set; }

        /// <summary>
        /// Human Player's Symbol "X" or "O"
        /// </summary>
        [JsonProperty(PropertyName = "humanPlayerSymbol")]
        public string HumanPlayerSymbol { get; set; }

        /// <summary>
        /// Current status of the game.
        /// "tie" Tie;
        /// "inconclusive" Game still on goin;
        /// "X" Player X won;
        /// "Y" Player Y won;
        /// </summary>
        [JsonProperty(PropertyName = "winner")]
        public string Winner { get; set; }

        /// <summary>
        /// Winner postions. The three pieces that won the game, otherwise
        /// null.
        /// </summary>
        [JsonProperty(PropertyName = "winPositions")]
        public IList<int?> WinPositions { get; set; }

        /// <summary>
        /// Current game board. '?' location empty,
        /// 'X' Player X has a piece on that location.
        /// 'O' Player O has a piece on that location.
        /// </summary>
        [JsonProperty(PropertyName = "gameBoard")]
        public IList<string> GameBoard { get; set; }

    }
}
