// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// API implementing TicTacToe move performed by a computer.
    /// </summary>
    public partial interface IRestClientSDKLibraryClient : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Subscription credentials which uniquely identify client
        /// subscription.
        /// </summary>
        ServiceClientCredentials Credentials { get; }


            /// <summary>
        /// Execute the computer's move, based on a player's move.
        /// </summary>
        /// Sample request where computer stars playing.
        /// Post
        /// {
        /// "move": 2,
        /// "azurePlayerSymbol": "X",
        /// "humanPlayerSymbol": "O",
        /// "gameBoard": ["?","?","?","?","?","?","?","?","?"]
        /// }
        /// <param name='body'>
        /// Status of the game, after the a player's move.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<TicTacToeMoveResultDto>> ExecuteMoveWithHttpMessagesAsync(TicTacToeMoveDto body = default(TicTacToeMoveDto), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

    }
}
